spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-video-dev
    username: root
    password: 123456

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB



mybatis:
  type-aliases-package: com.nly.pojo
  mapper-locations: classpath:mapper/*.xml


mapper:
  mappers: com.nly.utils.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8082
logging:
  level:
    com.nly.mapper: trace
#mybatis-plus:
#  global-config:
#    db-config:
#      #主键策略，依赖数据库的自增
#      id-type: auto
#  mapper-locations: classpath:mapper/*.xml
#  #配置实体类的别名
#  type-aliases-package: com.nly.pojo

#spring.datasource.druid.initial-size=1
#  spring.datasource.druid.min-idle=1
#  spring.datasource.druid.max-active=20
#  spring.datasource.druid.test-on-borrow=true

