spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-video-dev
    username: root
    password: 123456
    hikari:
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 60000
      #最大生命周期，0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 10
      #最大连接数量
      maximum-pool-size: 10

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000
    password: 123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB



mybatis:
  type-aliases-package: com.nly.pojo
  mapper-locations: classpath:mapper/*.xml


mapper:
  mappers: com.nly.utils.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true

server:
  port: 8083
logging:
  level:
    com.nly.mapper: trace

zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000


#mybatis-plus:
#  global-config:
#    db-config:
#      #主键策略，依赖数据库的自增
#      id-type: auto
#  mapper-locations: classpath:mapper/*.xml
#  #配置实体类的别名
#  type-aliases-package: com.nly.pojo

#spring.datasource.druid.initial-size=1
#  spring.datasource.druid.min-idle=1
#  spring.datasource.druid.max-active=20
#  spring.datasource.druid.test-on-borrow=true

