spring:
  redis:
    host: 118.24.157.179
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-video-dev?useUnicode=tru&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456